# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Time-TT
version:      0.000
version_from: lib/Time/TT.pm
installdirs:  site
requires:
    Date::JD:                      0.000
    LWP:                           5.53_94
    LWP::UserAgent:                
    Math::BigRat:                  0.04
    Math::Interpolator:            0.000
    Time::UTC:                     0.001

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
